---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gotify
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    global:
      fullnameOverride: *app
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: &group 1000
        fsGroup: *group
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      gotify:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gotify/server
              tag: 3.0.0
            env:
              TZ: America/New_York
              GOTIFY_SERVER_PORT: &port 8080
              GOTIFY_SERVER_SECURECOOKIE: "true"
              GOTIFY_DATABASE_DIALECT: postgres
              GOTIFY_DATABASE_CONNECTION:
                valueFrom:
                  secretKeyRef:
                    name: oke-cluster-pguser-gotify
                    key: uri
              GOTIFY_DEFAULTUSER_NAME:
                valueFrom:
                  secretKeyRef:
                    name: gotify-secrets
                    key: username
              GOTIFY_DEFAULTUSER_PASS:
                valueFrom:
                  secretKeyRef:
                    name: gotify-secrets
                    key: password
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: gotify
        ports:
          http:
            port: *port
    route:
      public:
        enabled: true
        kind: HTTPRoute
        hostnames: ["${GOTIFY_DOMAIN}"]
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - name: gotify
                port: *port
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: oci-bv
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /app/data
