---
# yaml-language-server: $schema=https://schemas.mafyuh.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app n8n
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    commonAnnotations:
      reloader.stakater.com/auto: "true"
    fullnameOverride: "n8n"
    image:
      repository: ghcr.io/n8n-io/n8n
      tag: 2.32.3
      pullPolicy: IfNotPresent
    config:
      timezone: America/New_York
    webhook:
      url: "https://${N8N_HOST}"
    queueMode:
      enabled: false
    replicaCount: 1
    resources:
      main:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
    database:
      type: postgresdb
      useExternal: true
      host: "oke-cluster-primary.databases.svc.cluster.local"
      port: 5432
      database: n8n
      schema: public
      user: n8n
      passwordSecret:
        name: oke-cluster-pguser-n8n
        key: password
      ssl:
        enabled: false
    redis:
      enabled: false
    secretRefs:
      existingSecret: n8n-secrets
