---
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.28.2
    container_name: dispatcharr
    environment:
      - TZ=America/New_York
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - DISPATCHARR_LOG_LEVEL=info
    volumes:
      - /docker/appdata/dispatcharr/data:/data:rw
    ports:
      - 9191:9191
    restart: unless-stopped
